version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/rust-api"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/rust-api/rust"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/sync-api-client"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/sync-api-common"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/sync-api-service"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/sync-api-tests"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/testbeds/component-model-async"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/testbeds/component-model-async"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/testbeds/component-model-performance"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/testbeds/component-model-performance"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/testbeds/component-model-vscode-2"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/testbeds/component-model-vscode-2"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/testbeds/component-model-vscode"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/testbeds/component-model-vscode"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/testbeds/component-model"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/testbeds/component-model"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/testbeds/cpp"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/testbeds/dotnet"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/testbeds/emccc-pure-wasi"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/testbeds/lsp-dotnet"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/testbeds/lsp-rust/client"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/testbeds/lsp-rust"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/testbeds/lsp-rust/server"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/testbeds/lsp-rust/server"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/testbeds/malloc"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/testbeds"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/testbeds/performance"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/testbeds/php"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/testbeds/python"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/testbeds/ruby"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/testbeds/rust-threads"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/testbeds/rust-threads"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/testbeds/rust"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/testbeds/rust"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/testbeds/threads"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/tools"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/wasi"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/wasm-component-model"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/wasm-kit"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/wasm-wasi-core"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/wasm-wasi-lsp"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/wasm-wasi/example"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/wasm-wasi"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/webshell"
      schedule:
          interval: "daily"
      versioning-strategy: increase
