name: Node

concurrency:
    group: Node-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    push:
        branches: [Current]
    pull_request:
        branches: [Current]
    workflow_call:

jobs:
    Pre-Publish:
        runs-on: ubuntu-latest

        env:
            ADBLOCK: true
            ASTRO_TELEMETRY_DISABLED: 1
            AUTOMATEDLAB_TELEMETRY_OPTOUT: 1
            AZURE_CORE_COLLECT_TELEMETRY: 0
            CHOOSENIM_NO_ANALYTICS: 1
            DIEZ_DO_NOT_TRACK: 1
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
            DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT: 1
            DO_NOT_TRACK: 1
            ET_NO_TELEMETRY: 1
            GATSBY_TELEMETRY_DISABLED: 1
            GATSBY_TELEMETRY_OPTOUT: 1
            GATSBY_TELEMETRY_OPT_OUT: 1
            GRIT_TELEMETRY_DISABLED: 1
            HASURA_GRAPHQL_ENABLE_TELEMETRY: false
            HINT_TELEMETRY: off
            HOMEBREW_NO_ANALYTICS: 1
            INFLUXD_REPORTING_DISABLED: true
            ITERATIVE_DO_NOT_TRACK: 1
            NEXT_TELEMETRY_DEBUG: 1
            NEXT_TELEMETRY_DISABLED: 1
            NG_CLI_ANALYTICS: false
            NUXT_TELEMETRY_DISABLED: 1
            PIN_DO_NOT_TRACK: 1
            POWERSHELL_TELEMETRY_OPTOUT: 1
            SAM_CLI_TELEMETRY: 0
            STNOUPGRADE: 1
            STRIPE_CLI_TELEMETRY_OPTOUT: 1
            TELEMETRY_DISABLED: 1

        strategy:
            matrix:
                node-version: [18, 19, 20]

        steps:
            - uses: actions/checkout@v4.1.7

            - uses: pnpm/action-setup@v4.0.0
              with:
                  version: 9.3.0
                  run_install: |
                      - recursive: true
                        args: [
                          --link-workspace-packages=true,
                          --lockfile-only,
                          --prefer-frozen-lockfile=false,
                          --shamefully-hoist=false,
                          --shared-workspace-lockfile=true,
                          --strict-peer-dependencies=false,
                          --unsafe-perm=true
                        ]

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./pnpm-lock.yaml

            - run: pnpm install
              working-directory: .

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-Node-${{ matrix.node-version }}-Target
                  path: ./Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./rust-api/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./rust-api

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-rust-api-Node-${{ matrix.node-version }}-Target
                  path: ./rust-api/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./sync-api-client/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./sync-api-client

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-sync-api-client-Node-${{ matrix.node-version }}-Target
                  path: ./sync-api-client/Target

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-sync-api-common-Node-${{ matrix.node-version }}-Target
                  path: ./sync-api-common/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./sync-api-service/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./sync-api-service

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-sync-api-service-Node-${{ matrix.node-version }}-Target
                  path: ./sync-api-service/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./sync-api-tests/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./sync-api-tests

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./testbeds/component-model-async/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./testbeds/component-model-async

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-component-model-async-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/component-model-async/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./testbeds/component-model-performance/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./testbeds/component-model-performance

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-component-model-performance-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/component-model-performance/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./testbeds/component-model-vscode-2/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./testbeds/component-model-vscode-2

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-component-model-vscode-2-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/component-model-vscode-2/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./testbeds/component-model-vscode/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./testbeds/component-model-vscode

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-component-model-vscode-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/component-model-vscode/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./testbeds/component-model/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./testbeds/component-model

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-component-model-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/component-model/Target

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-cpp-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/cpp/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./testbeds/dotnet/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./testbeds/dotnet

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-dotnet-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/dotnet/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./testbeds/lsp-rust/client/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./testbeds/lsp-rust/client

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-lsp-rust-client-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/lsp-rust/client/Target

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-lsp-rust-server-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/lsp-rust/server/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./testbeds/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./testbeds

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./testbeds/php/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./testbeds/php

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-php-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/php/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./testbeds/python/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./testbeds/python

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-python-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/python/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./testbeds/ruby/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./testbeds/ruby

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-ruby-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/ruby/Target

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-rust-threads-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/rust-threads/Target

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-rust-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/rust/Target

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-testbeds-threads-Node-${{ matrix.node-version }}-Target
                  path: ./testbeds/threads/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./tools/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./tools

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./wasi/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./wasi

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-wasi-Node-${{ matrix.node-version }}-Target
                  path: ./wasi/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./wasm-component-model/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./wasm-component-model

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-wasm-component-model-Node-${{ matrix.node-version }}-Target
                  path: ./wasm-component-model/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./wasm-kit/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./wasm-kit

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./wasm-wasi-core/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./wasm-wasi-core

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-wasm-wasi-core-Node-${{ matrix.node-version }}-Target
                  path: ./wasm-wasi-core/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./wasm-wasi-lsp/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./wasm-wasi-lsp

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-wasm-wasi-lsp-Node-${{ matrix.node-version }}-Target
                  path: ./wasm-wasi-lsp/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./wasm-wasi/example/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./wasm-wasi/example

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-wasm-wasi-example-Node-${{ matrix.node-version }}-Target
                  path: ./wasm-wasi/example/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./wasm-wasi/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./wasm-wasi

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-wasm-wasi-Node-${{ matrix.node-version }}-Target
                  path: ./wasm-wasi/Target

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./webshell/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./webshell

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.3
              with:
                  name: .-webshell-Node-${{ matrix.node-version }}-Target
                  path: ./webshell/Target
