name: NPM

concurrency:
    group: NPM-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    release:
        types: [created]
    workflow_call:

jobs:
    Publish:
        runs-on: ubuntu-latest

        env:
            ADBLOCK: true
            ASTRO_TELEMETRY_DISABLED: 1
            AUTOMATEDLAB_TELEMETRY_OPTOUT: 1
            AZURE_CORE_COLLECT_TELEMETRY: 0
            CHOOSENIM_NO_ANALYTICS: 1
            DIEZ_DO_NOT_TRACK: 1
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
            DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT: 1
            DO_NOT_TRACK: 1
            ET_NO_TELEMETRY: 1
            GATSBY_TELEMETRY_DISABLED: 1
            GATSBY_TELEMETRY_OPTOUT: 1
            GATSBY_TELEMETRY_OPT_OUT: 1
            GRIT_TELEMETRY_DISABLED: 1
            HASURA_GRAPHQL_ENABLE_TELEMETRY: false
            HINT_TELEMETRY: off
            HOMEBREW_NO_ANALYTICS: 1
            INFLUXD_REPORTING_DISABLED: true
            ITERATIVE_DO_NOT_TRACK: 1
            NEXT_TELEMETRY_DEBUG: 1
            NEXT_TELEMETRY_DISABLED: 1
            NG_CLI_ANALYTICS: false
            NUXT_TELEMETRY_DISABLED: 1
            PIN_DO_NOT_TRACK: 1
            POWERSHELL_TELEMETRY_OPTOUT: 1
            SAM_CLI_TELEMETRY: 0
            STNOUPGRADE: 1
            STRIPE_CLI_TELEMETRY_OPTOUT: 1
            TELEMETRY_DISABLED: 1
            TERRAFORM_TELEMETRY: 0

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4.1.7

            - uses: actions/setup-node@v4.0.2
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org"

            - run: npm install -g npm

            - name: Publish .
              continue-on-error: true
              working-directory: .
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./rust-api
              continue-on-error: true
              working-directory: ./rust-api
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./sync-api-client
              continue-on-error: true
              working-directory: ./sync-api-client
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./sync-api-common
              continue-on-error: true
              working-directory: ./sync-api-common
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./sync-api-service
              continue-on-error: true
              working-directory: ./sync-api-service
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/component-model-async
              continue-on-error: true
              working-directory: ./testbeds/component-model-async
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/component-model-performance
              continue-on-error: true
              working-directory: ./testbeds/component-model-performance
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/component-model-vscode-2
              continue-on-error: true
              working-directory: ./testbeds/component-model-vscode-2
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/component-model-vscode
              continue-on-error: true
              working-directory: ./testbeds/component-model-vscode
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/component-model
              continue-on-error: true
              working-directory: ./testbeds/component-model
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/cpp
              continue-on-error: true
              working-directory: ./testbeds/cpp
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/dotnet
              continue-on-error: true
              working-directory: ./testbeds/dotnet
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/lsp-rust/client
              continue-on-error: true
              working-directory: ./testbeds/lsp-rust/client
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/lsp-rust/server
              continue-on-error: true
              working-directory: ./testbeds/lsp-rust/server
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/php
              continue-on-error: true
              working-directory: ./testbeds/php
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/python
              continue-on-error: true
              working-directory: ./testbeds/python
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/ruby
              continue-on-error: true
              working-directory: ./testbeds/ruby
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/rust-threads
              continue-on-error: true
              working-directory: ./testbeds/rust-threads
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/rust
              continue-on-error: true
              working-directory: ./testbeds/rust
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./testbeds/threads
              continue-on-error: true
              working-directory: ./testbeds/threads
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./wasi
              continue-on-error: true
              working-directory: ./wasi
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./wasm-component-model
              continue-on-error: true
              working-directory: ./wasm-component-model
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./wasm-wasi-core
              continue-on-error: true
              working-directory: ./wasm-wasi-core
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./wasm-wasi-lsp
              continue-on-error: true
              working-directory: ./wasm-wasi-lsp
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./wasm-wasi/example
              continue-on-error: true
              working-directory: ./wasm-wasi/example
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./wasm-wasi
              continue-on-error: true
              working-directory: ./wasm-wasi
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./webshell
              continue-on-error: true
              working-directory: ./webshell
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
